<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>TinyBlueWhale.MinimalApi.Versioning</PackageId>   
    <Description>Centralized API version registry and versioned route integration for ASP.NET Core Minimal APIs.</Description>
    <PackageTags>dotnet;aspnetcore;minimal-api;api-versioning;versioning</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Mvc" />
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" />    
  </ItemGroup>

</Project>
