<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>TinyBlueWhale.MinimalApi.Endpoints</PackageId>    
    <Description>Modular endpoint discovery and automatic mapping for ASP.NET Core Minimal APIs.</Description>
    <PackageTags>dotnet;aspnetcore;minimal-api;endpoints;endpoint-discovery;vertical-slice</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />    
  </ItemGroup>

</Project>
