<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>TinyBlueWhale.MinimalApi</PackageId>
    <Description>Opinionated framework for modular and versioned ASP.NET Core Minimal APIs.</Description>
    <PackageTags>dotnet;aspnetcore;minimal-api;endpoints;versioning;vertical-slice</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TinyBlueWhale.MinimalApi.Endpoints\TinyBlueWhale.MinimalApi.Endpoints.csproj" />
    <ProjectReference Include="..\TinyBlueWhale.MinimalApi.Versioning\TinyBlueWhale.MinimalApi.Versioning.csproj" />
  </ItemGroup>

</Project>
