<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit.Analyzers" />
    <PackageReference Include="NUnit3TestAdapter" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TinyBlueWhale.MinimalApi.Endpoints\TinyBlueWhale.MinimalApi.Endpoints.csproj" />
    <ProjectReference Include="..\TinyBlueWhale.MinimalApi.Responses\TinyBlueWhale.MinimalApi.Responses.csproj" />
    <ProjectReference Include="..\TinyBlueWhale.MinimalApi.Versioning\TinyBlueWhale.MinimalApi.Versioning.csproj" />
    <ProjectReference Include="..\TinyBlueWhale.MinimalApi\TinyBlueWhale.MinimalApi.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="NUnit.Framework" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>
